name: Scan EC2 TLS

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Adjust workspace permissions
        run: chmod -R 777 "${{ github.workspace }}"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Download EC2 IP ranges
        run: |
          curl -s https://ip-ranges.amazonaws.com/ip-ranges.json | \
            jq -r '.prefixes[] | select(.service=="EC2") | .ip_prefix' > ec2_ranges.txt
          echo "Found EC2 ranges:"
          cat ec2_ranges.txt

      - name: Scan each EC2 range with ZMap
        run: |
          mkdir -p open_ips
          while read range; do
            echo "Scanning range: $range"
            # Create a file name based on the CIDR (replace '/' and '.' with underscores)
            fname=$(echo "$range" | tr '/.' '__')
            docker run --rm --network=host -v "${{ github.workspace }}":/data sec32/zmap zmap -M tcp_synscan -p 443 -B 100K "$range" -o /data/open_ips/open_ips_${fname}.csv
          done < ec2_ranges.txt

      - name: Combine open IP results
        run: |
          cat open_ips/*.csv > open_ips_all.csv
          echo "Total responsive IPs found: $(wc -l < open_ips_all.csv)"
          head -n 5 open_ips_all.csv

      - name: Run ZGrab2 to grab TLS certs
        run: |
          docker run --rm --network=host -v "${{ github.workspace }}":/data -i sec32/zgrab2 zgrab2 tls --port 443 --input-file=/data/open_ips_all.csv --output-file=/data/certs.json

      - name: Upload final certs.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: certs-json
          path: certs.json
