name: Fetch EC2 Ranges

on:
  workflow_dispatch:

jobs:
  fetch-ranges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Download and process EC2 IP ranges
        run: |
          echo "Downloading IP ranges from AWS..."
          curl -s https://ip-ranges.amazonaws.com/ip-ranges.json > ip-ranges.json
          
          echo "Extracting EC2 ranges..."
          jq -r '.prefixes[] | select(.service=="EC2") | .ip_prefix' ip-ranges.json > ec2_ranges.txt
          
          echo "Content of ec2_ranges.txt:"
          cat ec2_ranges.txt
          
          echo "Total ranges found: $(wc -l < ec2_ranges.txt)"

      - name: Commit and push changes
        run: |
          echo "Configuring git..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          echo "Adding file to git..."
          git add ec2_ranges.txt
          
          echo "Committing changes..."
          git commit -m "Update EC2 ranges $(date +'%Y-%m-%d')"
          
          echo "Pushing changes..."
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
