name: Scan Single EC2 Range

on:
  workflow_dispatch:
    inputs:
      ip_range:
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Pull latest to avoid conflicts
          git pull origin main

      - name: Setup range directory
        run: |
          RANGE_DIR="${{ github.workspace }}/results/${{ inputs.ip_range }}"
          mkdir -p "$RANGE_DIR"
          echo "RANGE_DIR=$RANGE_DIR" >> $GITHUB_ENV

      - name: Scan with ZMap
        run: |
          docker run --rm --network=host -v "${{ github.workspace }}":/data \
            sec32/zmap zmap -M tcp_synscan -p 443 -B 100K \
            "${{ inputs.ip_range }}" -o /data/open_ips.csv

      - name: Commit ZMap results
        run: |
          mv open_ips.csv "${{ env.RANGE_DIR }}/"
          git add "${{ env.RANGE_DIR }}/open_ips.csv"
          git commit -m "Add ZMap results for range ${{ inputs.ip_range }}"
          git pull --rebase origin main
          git push origin main

      - name: Run ZGrab2
        run: |
          docker run --rm --network=host -v "${{ github.workspace }}":/data -i \
            sec32/zgrab2 zgrab2 tls --port 443 \
            --input-file="${{ env.RANGE_DIR }}/open_ips.csv" \
            --output-file=/data/certs.json

      - name: Commit ZGrab2 results
        run: |
          mv certs.json "${{ env.RANGE_DIR }}/"
          git add "${{ env.RANGE_DIR }}/certs.json"
          git commit -m "Add ZGrab2 results for range ${{ inputs.ip_range }}"
          git pull --rebase origin main
          git push origin main
