name: Update AWS Route53 IPs and Scan Port 53

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-route53:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Adjust workspace permissions
        run: chmod -R 777 "${{ github.workspace }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate AWS Route53 IPs
        run: |
          python generate_candidates.py
          echo "Generated $(wc -l < aws_route53_ips.txt) IPs from Route53 ranges."

      - name: Commit Route53 IPs file
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update aws_route53_ips.txt"
          add: "aws_route53_ips.txt"
          author_name: "github-actions"
          author_email: "github-actions@github.com"

      - name: Upload Route53 IPs file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: aws_route53_ips.txt
          path: aws_route53_ips.txt

      - name: Run masscan for port 53
        run: |
          echo "[*] Running masscan on port 53 for Route53 IPs..."
          docker run --rm \
            -v "${{ github.workspace }}":/data \
            ilyaglow/masscan \
            -p53 \
            -iL /data/aws_route53_ips.txt \
            -oL /data/open53.txt \
            --wait 10

      - name: Extract open port 53 IPs
        run: |
          echo "[*] Extracting IPs with port 53 open..."
          grep '^open tcp 53 ' open53.txt | awk '{print $4}' | sort -u > aws_ns_ips_53.txt
          echo "[*] IPs with port 53 open (aws_ns_ips_53.txt):"
          cat aws_ns_ips_53.txt

      - name: Commit scan results
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update scan results for Route53 port 53"
          add: |
            aws_route53_ips.txt
            open53.txt
            aws_ns_ips_53.txt
          author_name: "github-actions"
          author_email: "github-actions@github.com"

      - name: Upload scan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Scan Results
          path: |
            aws_route53_ips.txt
            open53.txt
            aws_ns_ips_53.txt
