name: ZGrab2 Certificate Collection

on:
  workflow_dispatch:
    inputs:
      start_line:
        description: 'Start processing from line number (1-based)'
        required: true
        type: number
      batch_size:
        description: 'Number of ranges to process'
        required: true
        type: number
        default: 1

jobs:
  collect-certs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup workspace
        run: |
          mkdir -p cert_results
          chmod -R 777 "${{ github.workspace }}"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Process ranges with ZGrab2
        run: |
          process_zgrab_output() {
            local input_file="$1"
            local output_file="$2"
            
            if [ ! -s "$input_file" ]; then
              echo "Empty or missing input file: $input_file"
              echo '{
                "certificates": [],
                "total_count": 0,
                "scan_time": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"
              }' > "$output_file"
              return
            fi
            
            echo "Processing certificates..."
            local temp_file="temp_processed.json"
            : > "$temp_file"
            
            # Process each line and clean nulls
            while IFS= read -r line; do
              if [ -n "$line" ]; then
                echo "$line" | jq -c '
                  select(.data != null and .data.tls != null) | 
                  {
                    ip,
                    tls: (.data.tls | {
                      protocol_version: .result.handshake_log.server_hello.version.name,
                      cipher_suite: (.result.handshake_log.server_hello.cipher_suite | {
                        name: .name,
                        value: .value
                      }),
                      certificate_details: (.result.handshake_log.server_certificates.certificate.parsed | {
                        validity: (.validity | {
                          start,
                          end
                        }),
                        issuer: {
                          common_name: .issuer.common_name[0],
                          organization: .issuer.organization[0],
                          country: .issuer.country[0]
                        },
                        subject: {
                          common_name: .subject.common_name[0]
                        },
                        public_key: (.subject_key_info | {
                          algorithm: .key_algorithm.name,
                          length: .rsa_public_key.length
                        }),
                        extensions: (.extensions | {
                          basic_constraints: { is_ca },
                          key_usage: { digital_signature, key_encipherment },
                          subject_alt_name: { dns_names }
                        }),
                        security_features: (.result.handshake_log.server_hello | {
                          ocsp_stapling,
                          secure_renegotiation,
                          extended_master_secret
                        }),
                        signature: (.signature | {
                          algorithm: .signature_algorithm.name,
                          valid
                        })
                      }),
                      security_audit: {
                        certificate_chain: [
                          .result.handshake_log.server_certificates.chain[]? | 
                          select(. != null) | {
                            issuer_common_name: .parsed.issuer.common_name[0],
                            valid: .parsed.signature.valid
                          }
                        ],
                        browser_trusted: .result.handshake_log.server_certificates.validation.browser_trusted
                      }
                    })
                  } | del(..|nulls)' >> "$temp_file" || true
              fi
            done < "$input_file"
            
            if [ -s "$temp_file" ]; then
              # Filter out empty objects and arrays
              jq -s '
                map(select(. != null) | with_entries(
                  select(
                    .value != null and 
                    .value != [] and 
                    (.value | type == "object" | not or . != {})
                  )
                )) |
                {
                  certificates: .,
                  total_count: length,
                  scan_time: "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"
                }' "$temp_file" > "$output_file"
            else
              echo '{
                "certificates": [],
                "total_count": 0,
                "scan_time": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"
              }' > "$output_file"
            fi
            
            rm -f "$temp_file"
          }

          # Process each range
          START_LINE=${{ inputs.start_line }}
          END_LINE=$((START_LINE + ${{ inputs.batch_size }} - 1))
          
          while IFS= read -r cidr; do
            [ -z "$cidr" ] && continue
            
            echo "Processing range: $cidr"
            safe_name=$(echo "$cidr" | tr '/' '_')
            
            # Check if ZMap results exist
            zmap_result="zmap_results/${safe_name}.json"
            if [ ! -f "$zmap_result" ]; then
              echo "No ZMap results found for $cidr, skipping..."
              continue
            fi
            
            mkdir -p "cert_results/${safe_name}"
            jq -r '.ips[]?' "$zmap_result" > "tmp_ips.txt" 2>/dev/null
            
            if [ -s tmp_ips.txt ]; then
              echo "Running ZGrab2 for ${safe_name}..."
              
              if docker run --rm --network=host -v "${{ github.workspace }}":/data -i \
                sec32/zgrab2 zgrab2 tls --port 443 \
                --timeout 10s \
                --input-file=/data/tmp_ips.txt \
                --output-file=/data/tmp_certs.json; then
                
                process_zgrab_output "tmp_certs.json" "cert_results/${safe_name}/certs.json"
                
                if [ -f "cert_results/${safe_name}/certs.json" ]; then
                  total_certs=$(jq '.total_count' "cert_results/${safe_name}/certs.json")
                  trusted_certs=$(jq '[.certificates[].tls.security_audit.browser_trusted] | map(select(. == true)) | length' "cert_results/${safe_name}/certs.json")
                  echo "{
                    \"range\": \"$cidr\",
                    \"total_certificates\": $total_certs,
                    \"browser_trusted_certificates\": $trusted_certs,
                    \"scan_time\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"
                  }" > "cert_results/${safe_name}/summary.json"
                  
                  echo "Processed $total_certs certificates ($trusted_certs browser-trusted) for $cidr"
                else
                  echo "Failed to create output file for $cidr"
                fi
              else
                echo "ZGrab2 scan failed for range: $cidr"
              fi
            else
              echo "No IPs found in ZMap results for range: $cidr"
            fi
            
            rm -f tmp_ips.txt tmp_certs.json
          done < <(awk "NR >= $START_LINE && NR <= $END_LINE" ec2_ranges.txt)
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add cert_results/ || true
          git commit -m "Add certificate scan results for ranges $START_LINE-$END_LINE" || true
          git push || {
            git pull --rebase
            git push
          }
