name: ZMap Port 443 Scan

on:
  workflow_dispatch:
    inputs:
      start_line:
        description: 'Start processing from line number (1-based)'
        required: true
        type: number
      batch_size:
        description: 'Number of ranges to process'
        required: true
        type: number
        default: 1

jobs:
  zmap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup workspace
        run: |
          mkdir -p zmap_results
          chmod -R 777 "${{ github.workspace }}"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Make sure we're on a clean state
          git fetch origin
          git reset --hard origin/main

      - name: Process ranges with ZMap
        run: |
          # Helper function to process ZMap results
          process_zmap_results() {
            local result_file="$1"
            local cidr="$2"
            local timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            
            # Count successful lines
            local total_ips=$(wc -l < tmp_open_ips.csv || echo "0")
            
            # Create JSON output
            jq -n --arg cidr "$cidr" \
               --arg time "$timestamp" \
               --arg total "$total_ips" \
               --slurpfile ips tmp_open_ips.csv \
              '{
                range: $cidr,
                scan_time: $time,
                total_ips: ($total|tonumber),
                ips: $ips
              }' > "$result_file"
          }

          START_LINE=${{ inputs.start_line }}
          END_LINE=$((START_LINE + ${{ inputs.batch_size }} - 1))
          
          # Process each range
          while IFS= read -r cidr; do
            [ -z "$cidr" ] && continue
            
            echo "Processing range: $cidr"
            safe_name=$(echo "$cidr" | tr '/' '_')
            result_file="zmap_results/${safe_name}.json"
            
            echo "Running ZMap scan for $cidr"
            if timeout 30m docker run --rm --network=host -v "${{ github.workspace }}":/data \
              sec32/zmap zmap -M tcp_synscan -p 443 -B 100K \
              --cooldown-time=2 \
              "$cidr" -o "/data/tmp_open_ips.csv"; then
              
              if [ -s tmp_open_ips.csv ]; then
                echo "Found open ports, processing results..."
                process_zmap_results "$result_file" "$cidr"
                
                # Create summary file
                total_ips=$(jq '.total_ips' "$result_file")
                echo "Scan completed successfully for $cidr - Found $total_ips active hosts"
                
              else
                echo "No open ports found for range: $cidr"
                echo "{
                  \"range\": \"$cidr\",
                  \"scan_time\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\",
                  \"total_ips\": 0,
                  \"ips\": []
                }" > "$result_file"
              fi
            else
              echo "ZMap scan failed for range: $cidr"
              echo "{
                \"range\": \"$cidr\",
                \"scan_time\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\",
                \"error\": \"scan_timeout\",
                \"total_ips\": 0,
                \"ips\": []
              }" > "$result_file"
            fi
            
            # Cleanup temporary files
            rm -f tmp_open_ips.csv
            
            # Commit and push after each range
            if [ -f "$result_file" ]; then
              # Create summary.json if it doesn't exist
              if [ ! -f "zmap_results/summary.json" ]; then
                echo '{"scans":[]}' > "zmap_results/summary.json"
              fi
              
              # Update summary.json
              jq --arg range "$cidr" \
                 --arg time "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
                 --arg total "$(jq '.total_ips' "$result_file")" \
                '.scans += [{
                  range: $range,
                  scan_time: $time,
                  total_ips: ($total|tonumber)
                }]' "zmap_results/summary.json" > "zmap_results/summary.json.tmp" && \
              mv "zmap_results/summary.json.tmp" "zmap_results/summary.json"
              
              # Try to commit and push changes
              git add "$result_file" "zmap_results/summary.json"
              if git commit -m "Add ZMap scan results for $cidr"; then
                # Attempt to push, if fails, pull and try again
                if ! git push origin main; then
                  echo "Push failed, trying to merge remote changes..."
                  git pull --rebase origin main
                  git push origin main || {
                    echo "Failed to push even after rebase. Storing results locally."
                  }
                fi
              fi
            fi
          done < <(awk "NR >= $START_LINE && NR <= $END_LINE" ec2_ranges.txt)
